FROM ruby:2.7-buster
ENV APP_HOME /analitycs
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ENV BUNDLE_PATH /bundle
COPY ./Gemfile.lock $APP_HOME
COPY ./Gemfile $APP_HOME
RUN curl -fsSL https://deb.nodesource.com/setup_17.x | bash -
RUN apt-get install -y nodejs imagemagick
RUN gem install bundler -v 2.2.31 && gem install foreman
RUN bundle config set --local without 'development test'
RUN bundle install --jobs 4

CMD tail -f /dev/null
